<?php

/**
 * @file
 * Contains persian_alterchar.module.
 */

 use Drupal\field\Entity\FieldConfig;

 
 function persian_alterchar_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
   
  /* Check whether it's a node */
  if ($entity instanceof \Drupal\node\NodeInterface) {
    // Replacement function
    function replaceChar($string) {
      $replacement_pattern = array ("ي", "ك", "٤", "٥", "٦"); 
      $persian_replacement = array("ی", "ک", "۴", "۵", "۶");
      $result = $string;
      $result = str_replace($replacement_pattern, $persian_replacement, $string);
      return $result;
    }

    // Node title
    $nodeTitle = $entity->getTitle();
    $entity->setTitle(replaceChar($nodeTitle));

    // Body main
    if(!empty($entity->body->value)) {
      $entity->body->value = replaceChar($entity->body->value);
    }

    // Body Summary
    if(!empty($entity->body->summary)) {
      $entity->body->summary = replaceChar($entity->body->summary);
    }

    // Only custom text fields
    $fields = $entity->getFieldDefinitions();  
    foreach ($fields as $field) {
      $fieldType = $field->getType();
      
      if ($fieldType == 'string') {
        $field = replaceChar($field);
      } else
      return;
    }
  }

  /* Check whether it's a taxonomy term */
  if ($entity instanceof \Drupal\taxonomy\Entity\Term) {
    $entity->name->value = replaceChar($entity->name->value);
    if(!empty($entity->description->value)) {
      $entity->description->value = replaceChar($entity->description->value);
    }
  }

}
